### ISSUE TITLE
Add source code editor

### ISSUE THREAD

**Issue by justinmacorin** [promptdesk/promptdesk#2]
Implement a source code editor instead of using a HTML contenteditable DIV for the model editor.

**Reasoning:** Validating, writing, and reading JSON is challenging with no styling. A source code editor can help with this. In addition, it can be used for future source-code related features - like code execution, source code modification, etc.

Files:
- frontend/pages/models.tsx (modify the contenteditable pre tag)
- NEW CodeEditor.tsx file

Here is an example of a good code editor: https://microsoft.github.io/monaco-editor/

**Comment by Nasirahamad88** [comment]
I come from Upwork to help you

**Comment by chirayu-wal** [comment]
Hi @justinmacorin I am coming from the job on upwork. I worked on this issue and wanted to share the results. Below I have attached the screenshot with the solution. Please let me know if you think this is the required solution or if there are any changes required. Thank you.
Hi @justinmacorin I am coming from the job on upwork. I worked on this issue and wanted to share the results. I have also applied for the job on upwork. Below I have attached the screenshots with the solution. Please let me know if you think this is the required solution or if there are any changes required. Thank you.

<img width="1440" alt="Screenshot 2023-11-19 at 3 59 49 PM" src="https://github.com/promptdesk/promptdesk/assets/85103916/09201519-f63a-4b39-9ff5-b8dbcf283cd3">
<img width="1440" alt="Screenshot 2023-11-19 at 3 59 54 PM" src="https://github.com/promptdesk/promptdesk/assets/85103916/284d6029-7b41-48f1-b5f5-84caa2f9ed6f">
<img width="1440" alt="Screenshot 2023-11-19 at 3 59 59 PM" src="https://github.com/promptdesk/promptdesk/assets/85103916/e877b303-866b-4f7d-90fa-c448ddb13cd1">
