### ISSUE TITLE
BUG: Logs page is missing divider line below page heading

### ISSUE THREAD

**Issue by BhuvaneshPatil** [promptdesk/promptdesk#27]
Other pages have a line to divide heading/navbar and content
<img width="1493" alt="Screenshot 2024-02-04 at 10 59 33 PM" src="https://github.com/promptdesk/promptdesk/assets/27822551/e3338e7c-6dd1-4387-8b4b-f321be891b7d">
<img width="1305" alt="Screenshot 2024-02-04 at 10 59 43 PM" src="https://github.com/promptdesk/promptdesk/assets/27822551/81a53558-0325-4369-b86c-c03f0588b2f5">

Logs page doesn't have that
<img width="1327" alt="Screenshot 2024-02-04 at 10 59 26 PM" src="https://github.com/promptdesk/promptdesk/assets/27822551/ba2a38ee-359a-4e41-95e6-db7a091b2cb1">

**Comment by seattlereactdev** [comment]
<img width="1436" alt="image" src="https://github.com/promptdesk/promptdesk/assets/98289721/10add8c2-f436-4b96-a5f4-44e2c612e7e8">

<img width="1440" alt="image" src="https://github.com/promptdesk/promptdesk/assets/98289721/94678214-6d1d-4846-8c81-ac9f5b013a1e">

Hmmm.... We're trying to follow the following OpenAI pattern from a UI/UX perspective.

**Comment by BhuvaneshPatil** [comment]
Oh. Got it. Closing this one
