### ISSUE TITLE
FEATURE - Add Edit Model, Edit Prompt, View Sampels buttons on specific logs page.

### ISSUE THREAD

**Issue by BhuvaneshPatil** [promptdesk/promptdesk#47]

**Comment by BhuvaneshPatil** [comment]
https://github.com/promptdesk/promptdesk/assets/27822551/abd83400-348b-449d-9418-198a40a5f803


@justinmacorin can you please verify if this is works or do we need to place them at some other place?

**Comment by justinmacorin** [comment]
@BhuvaneshPatil - I was thinking this should go here: 
<img width="1250" alt="image" src="https://github.com/promptdesk/promptdesk/assets/47508868/3e136055-40d3-40c1-979b-4feb53298894">

Similar to how we have buttons here:
<img width="1268" alt="image" src="https://github.com/promptdesk/promptdesk/assets/47508868/cb5d349e-e130-4dcc-b59c-c9006499c2a2">

Buttons:
[Prompt] [Model] [Samples]

Let me know your thoughts!

**Comment by BhuvaneshPatil** [comment]
Okay, Got it. I thought we wanted to go to that particular model or prompt for that log.
